language: php

notifications:
  email:
    on_success: never

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n
  - composer global require edgedesign/phpqa=v1.20.0 --update-no-dev

script:
  - composer test -- --coverage-clover=coverage.xml
  - composer cs-fix
  - composer phpstan
  - composer psalm
  - phpqa --report --ignoredDirs vendor

after_success:
- bash <(curl -s https://codecov.io/bash)
